version: "3.4"

services:
    flask:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
            - ./data/nginx/conf/:/etc/nginx/conf.d/:ro
            - ./data/certbot/conf:/etc/letsencrypt:ro
            - ./data/certbot/www:/var/www/certbot:ro
        ports:
            - "80:80"
            - "443:443"
        restart: always
        networks:
            - flask-networks
    certbot:
      image: certbot/certbot:latest
      volumes:
        - ./data/certbot/www:/var/www/certbot:rw
        - ./data/certbot/conf:/etc/letsencrypt:rw

networks:
    flask-networks:
        driver: bridge