version: "3.7"

services:
    flask:
        container_name: 'flask'
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        ports:
            - "3000:80"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            CFLAGS: -Qunused-arguments
            CPPFLAGS: -Qunused-arguments
            FLASK_ENV: production
            PROD_DATABASE_URI: postgresql://root:password@postgres:5432/flaskdb
        networks:
            - flask-networks
    postgres:
        container_name: 'postgres'
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: flaskdb        
        volumes:
            - ./data/:/var/dump
            - ./db_data/:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U root -d flaskdb"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - flask-networks

networks:
    flask-networks:
        driver: bridge